version: '3'

services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    laravel:
        build: ./laravel
        volumes:
            - ./source:/var/www/html
    redis:
        image: redis:latest
        ports:
            - 6379:6379